; PulseSensor dashboard for Waveshare ESP32-S3-RLCD-4.2

[platformio]
default_envs = waveshare_rlcd42

[env:waveshare_rlcd42]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.flash_freq = 80m
board_build.f_cpu = 240000000L
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
framework = arduino
upload_speed = 921600
upload_port = /dev/cu.usbmodem2101
monitor_speed = 115200
monitor_port = /dev/cu.usbmodem2101
monitor_filters = default, esp32_exception_decoder
build_type = release

lib_deps =
	adafruit/Adafruit GFX Library
	worldfamouselectronics/PulseSensor Playground@2.1.1

build_flags =
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCORE_DEBUG_LEVEL=0
	-DAPP_VERSION=\"0.4.41-snappy-lock-rlcd\"
	-DPULSE_PIN=1
